sudo: required
services: docker
language: python
install:
  - pip install docker molecule openshift jmespath mcstatus
env:
  - ANSIBLE_VERBOSITY=3
jobs:
  include:
  - name: minecraft
    stage: test
    script:
    - cd traditional/minecraft
    - molecule test
  - name: minecraft-kubernetes
    script:
    - cd kubernetes
    - molecule test
  - name: minecraft-kubernetes-operator
    script:
    - cd kubernetes
    - molecule test -s operator
