---

- name: Create a Minecraft CR that does not agree to the EULA
  k8s:
    api_version: '{{ api_version }}'
    kind: '{{ kind }}'
    name: '{{ name }}'
    namespace: '{{ namespace }}'
    wait: yes
    wait_timeout: 60
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  register: teula_cr_result

- name: Assert that an address has been set on the custom resource
  assert:
    that: teula_cr_result.result.status.address is defined

- import_tasks: test_not_reachable.yml
  vars:
    address: '{{ teula_cr_result.result.status.address  }}'
    seconds: 30

# This is good practice but bad for demos
# - name: Delete the Minecraft instance
#   k8s:
#     state: absent
#     api_version: '{{ api_version }}'
#     kind: '{{ kind }}'
#     name: '{{ name }}'
#     namespace: '{{ namespace }}'
#     wait: yes
