---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length:
        max: 120
platforms:
- name: kind-test-local
  groups:
  - k8s
  image: bsycorp/kind:latest-1.14
  privileged: True
  override_command: no
  exposed_ports:
    - 8443/tcp
    - 10080/tcp
  published_ports:
    - 0.0.0.0:${TEST_CLUSTER_PORT:-10443}:8443/tcp
  pre_build_image: yes
  volumes:
    - ${MOLECULE_PROJECT_DIRECTORY}:/build:Z
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-default}
        api_version: demos.fabianism.us/v1alpha1
        kind: Minecraft
        kubeconfig: ${MOLECULE_EPHEMERAL_DIRECTORY}/.kubeconfig
  env:
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/.kubeconfig
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/.kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-10443}'
verifier:
  name: ansible
  lint:
    name: ansible-lint
